pythonanywhere/pythonanywhere/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^quiz/', include('quiz.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
]

pythonanywhere/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^answer/$', views.answer, name='answer'),
    url(r'^result/$', views.result, name='result'),
    url(r'^quizanswer/$', views.quizanswer, name='quizanswer'),
    url(r'^ranking/$', views.ranking, name='ranking')
]

pythonanywhere/quiz/models.py
from __future__ import unicode_literals

from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    #pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    answer = models.BooleanField(default=False)
    def __str__(self):
        return self.choice_text

class User_answer(models.Model):
    user_name = models.CharField(max_length=20)
    score = models.IntegerField(default=0)
    def __str__(self):
        return self.user_name

pythonanywhere/quiz/views.py
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse ,Http404
from django.urls import reverse
from .models import Choice, Question ,User_answer

def index(request):
    return render(request, 'quiz/index.html')

def answer(request):
    context = {'question': Question.objects.all()}
    return render(request, 'quiz/answer.html',context)

def result(request):
    choice_all = Choice.objects.count()
    question_all = Question.objects.count()
    score = 0
    for i in range(1,choice_all):
    	checkans = str(request.POST.get(str(i),False))
        if checkans == 'True':
            score += 1
    user_name = request.POST.get('uname',False)
    u = User_answer(user_name=user_name,score=score)
    u.save()
    context = {'score':score,'question':question_all,'uname':user_name}
    return render(request, 'quiz/result.html',context)

def quizanswer(request):
    context = {'question': Question.objects.all()}
    return render(request, 'quiz/quizanswer.html',context)

def ranking(request):
    topscore_list = User_answer.objects.order_by('-score')[:20]
    context = {'user': topscore_list}
    return render(request, 'quiz/ranking.html',context)

pythonanywhere/quiz/templates/quiz/answer.html
<h1>Quiz about Prayut.</h1>

<form action="{% url 'quiz:result'%}" method="post">
{% csrf_token %}
{% for data in question.all %}
   {{ forloop.counter }}. 
   {{data.question_text}}
   {% for choice in data.choice_set.all %}
      <br>
       <input type="radio" name="{{data.id}}" id="choice{{forloop.counter}}" value="{{choice.answer}}">
      {{choice.choice_text}}
   {% endfor %}
<br>
{% endfor %}
<br>
Enter your name.(Required)
<br>
<input type="text" name="uname" required/>
<br>
<input type="Submit" value="Submit your answer." />
<br>
</form>

pythonanywhere/quiz/templates/quiz/index.html
<html>
    <body bgcolor="black" text="white">
    <style>
    h1 {
    color: white;
    font-family: courier;
    font-size: 400%;
}
    h2 {
    color: white;
    font-family: Verdana;
    font-size: 250%;
}
div {
    background-color:#696871;
    color:white;
    padding:30px;
}
nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
    font-size: 150%
}
article {
    margin-left: 300px;
    border-left: 1px solid gray;
    padding: 1em;

}
</style>

<div>
<h1><center><a name="Building Software 2">Building Software 2</h1></center>
</div>

<nav>
<b>
<p><a href="#ไอดอลของฉัน">ไอดอลของฉัน</p>
<p><a href="#ประวัติส่วนตัว">ประวัติส่วนตัว</p>
<p><a href="#ชื่อเสียงและเกียรติยศ">ชื่อเสียงและเกียรติยศ</p>
<p><a href="#ผลงานที่โดดเด่น">ผลงานที่โดดเด่น</p>
<p><a href="#แหล่งอ้างอิง">ที่มาของข้อมูล</p>
<p><a href="{% url 'quiz:answer' %}">ทำ QUIZ แฟนพันธุ์แท้นายก!!</p>
</b>
</nav>

<article>
<center>
<h2><ins><a name="ไอดอลของฉัน"</ins>ไอดอลของฉัน</h2>
<img src="http://news.asiaone.com/sites/default/files/original_images/Jan2015/20150127_prayutchanocha-khakis_thenation.jpg" style="width:600px;height:450px; margin="auto";>
<p>พลเอก ประยุทธ์ จันทร์โอชา นายกรัฐมนตรี</p>
<a href="#Building Software 2">ไปข้างบนสุด</a>
<hr width="1000">
<h2><ins><a name="ประวัติส่วนตัว">ประวัติส่วนตัว</ins></h2>
<img src="http://www.abc.net.au/news/image/5591820-3x2-940x627.jpg" style="width:600px;height:450px; margin="auto";>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp พลเอก ประยุทธ์ จันทร์โอชา เกิดวันที่ 21 มีนาคม 2497 ที่จังหวัดนครราชสีมา เป็นบุตรชายของ พันเอก (พิเศษ) ประพัฒน์ จันทร์โอชา กับเข็มเพชร จันทร์โอชา มารดารับราชการครู และเป็นผู้อนุบาล พันเอก (พิเศษ) ประพัฒน์ จันทร์โอชา มีชื่อเล่นว่า "ตู่" สื่อมวลชนนิยมเรียกว่า "บิ๊กตู่" เป็นบุตรชายคนโตจากพี่น้องทั้งหมดสี่คน ได้แก่ประคัลภ์ จันทร์โอชา พลอากาศตรีหญิง ประกายเพชร จันทร์โอชา ผู้ทรงคุณวุฒิกองทัพอากาศ และพลเอก ปรีชา จันทร์โอชา อดีตปลัดกระทรวงกลาโหม อดีตผู้ช่วยผู้บัญชาการทหารบก สมรสกับรองศาสตราจารย์ นราพร จันทร์โอชา รองประธานมูลนิธิการศึกษา</p>
<a href="#Building Software 2">ไปข้างบนสุด</a>
<hr width="1000">
<h2><ins><a name="เกียรติยศและชื่อเสียง">เกียรติยศและชื่อเสียง</ins></h2>
<img src="http://www.dw.com/image/17662392_303.jpg" style="width:700px;height:450px; margin="auto";>
</center>
<p>
<ul>
  <li>>ดำรงตำแหน่งนายกรัฐมนตรีไทย คนที่ 29 ของประเทศไทย วันที่ 24 สิงหาคม 2557</li>
  <li>เคยดำรงตำแหน่งผู้บัญชาการทหารบก (1 ตุลาคม 2553 – 30 กันยายน 2557)</li>
  <li>เคยดำรงตำแหน่งแม่ทัพภาคที่ (11 ตุลาคม 2549 – 30 กันยายน 2551)</li>
  <li>เครื่องราชอิสริยาภรณ์อันเป็นที่เชิดชูยิ่งช้างเผือก ชั้นสูงสุด มหาปรมาภรณ์ช้างเผือก (ม.ป.ช.)</li>
  <li>เครื่องราชอิสริยาภรณ์อันมีเกียรติยศยิ่งมงกุฎไทย ชั้นสูงสุด มหาวชิรมงกุฎ (ม.ว.ม.)</li>
  <li>อื่นๆอีกมากมาย
</ul>
</p>
<center>
<a href="#Building Software 2">ไปข้างบนสุด</a>
<hr width="1000">
<h2><ins><a name="ผลงานที่โดดเด่น">ผลงานที่โดดเด่น</ins></h2>
<img src="http://media.gettyimages.com/photos/thai-prime-minister-prayut-chanocha-claps-his-hands-during-a-welcome-picture-id463038922" style="width:700px;height:450px; margin="auto";>
</center>
<p>
<ul>
  <li>ด้านความมั่นคง ได้นำประเทศชาติที่ตกอยู่ในสภาพรัฐล้มเหลวกลับมาสู่ความเป็นนิติรัฐที่ยึดหลักนิติธรรม
ประชาชนดำเนินชีวิตประจำวันได้อย่างเป็นปรกติสุข เพราะบ้านเมืองมีความสงบเรียบร้อย การก่อเหตุร้ายใน 3 จังหวัดภาคใต้ลดลง
ความสัมพันธ์กับประเทศเพื่อนบ้านมีความเข้าใจเป็นอันดีต่อกันและดำเนินไปอย่างราบรื่น</li>
  <li>ด้านเศรษฐกิจ ได้ใช้นโยบายกระตุ้นเศรษฐกิจโดยรัฐเป็นผู้ลงทุนในโครงการขนาดใหญ่ด้านสาธารณูปโภคและสาธารณูปการ
เพื่อให้ประเทศไทยเป็นศูนย์กลางการคมนาคมขนส่งของประชาคมเศรษฐกิจอาเซียนอย่างสมบูรณ์แบบ มีมาตรการให้การช่วยเหลือภาคเกษตรกรรม
 ภาคอุตสาหกรรมและภาคพาณิชยกรรม และภาคธุรกิจบริการอย่างทั่วถึง</li>
  <li>ด้านสังคม มีการบังคับใช้กฎหมายเพื่อจัดระเบียบสังคมอย่างจริงจัง ประชาชนไม่ถูกอิทธิพลมืดข่มขู่และคุกคาม มีการทวงคืนทรัพยากรธรรมชาติ
และป่าไม้ที่มีการครอบครองโดยผิดกฎหมาย จัดสรรที่ดินทำกินให้แก่ประชาชนผู้ยากไร้ได้ทำประโยชน์</li>
</ul>
</ul>
</p>
<center>
<a href="#Building Software 2">ไปข้างบนสุด</a>
<hr width="1000">
<h2><ins><a name="แหล่งอ้างอิง">แหล่งอ้างอิง</ins></h2>
</center>
<p>
<ul>
  <li><a href="http://www.dailynews.co.th/article/525501">http://www.dailynews.co.th/article/525501</a></li>
  <li><a href="http://www.w3schools.com/html">http://www.w3schools.com/html</a></li>
  <li><a href="https://th.wikipedia.org/wiki/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A2%E0%B8%B8%E0%B8%97%E0%B8%98%E0%B9%8C_%E0%B8%88%E0%B8%B1%E0%B8%99%E0%B8%97%E0%B8%A3%E0%B9%8C%E0%B9%82%E0%B8%AD%E0%B8%8A%E0%B8%B2">https://th.wikipedia.org/wiki/ประยุทธ์_จันทร์โอชา</a></li>
</ul>
</p>
<center>
<a href="#Building Software 2">ไปข้างบนสุด</a>
<hr width="1000">
</center>
</article>

</body>
</html>

pythonanywhere/quiz/templates/quiz/quizanswer.html
<h1>Answer of all questions.</h1>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />
</head>
<body>

<table style="width:100%">
  <tr>
    <th>Question_id</th>
    <th>Question</th>
    <th>Answer</th> 
  </tr>
{% for data in question.all %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{data.question_text}}</td>
   {% for choice in data.choice_set.all %}
       {% if choice.answer %}
           <td>{{choice.choice_text}}<br>
       {% endif %}
   {% endfor %}
  </td></tr>
{% endfor %}
</table>

</body>
</html>
<a href="{% url 'quiz:index' %}">กลับหน้าแรก<br>

pythonanywhere/quiz/templates/quiz/ranking.html
<h1>Ranking of users.</h1>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 15px;
}
</style>
</head>
<body>

<table style="width:100%">
  <tr>
    <th>Ranking</th>
    <th>Name</th>
    <th>Score</th> 
  </tr>
{% for user in user.all %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{user.user_name}}</td>
    <td>{{user.score}}</td>
  </tr>
{% endfor %}
</table>

</body>
</html>
<a href="{% url 'quiz:index' %}">กลับหน้าแรก<br>

pythonanywhere/quiz/templates/quiz/result.html
<h1>{{uname}}!!</h1>
<h1>Your score is {{score}} /{{question}}.</h1>
<br>
<a href="{% url 'quiz:quizanswer' %}">ดูเฉลยควิซ<br>
<a href="{% url 'quiz:ranking' %}">ดู Top Ranking 20 อันดับแรก<br>
<a href="{% url 'quiz:index' %}">กลับหน้าแรก<br>